<a href="https://colab.research.google.com/github/NikilaYN/ML---series/blob/main/Tensors-Machine%20learning/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensors

####0-D tensor (single numbers)

In [ ]:
import numpy as np

In [ ]:
a=np.array(2)

In [ ]:
a

array(2)

In [ ]:
a.ndim

0

###1-D tensor (vector)

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr.ndim

1

####2-D Tensors(Matrices)

In [ ]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat.ndim

2

####3-D tensors

In [ ]:
mylist=np.array([[[1,2,3],[100,200,300],[4,5,6]],[[7,8,9],[400,500,600],[10,11,12]],[[13,14,15],[700,800,900],[16,17,18]]])

In [ ]:
mylist

array([[[  1,   2,   3],
        [100, 200, 300],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [400, 500, 600],
        [ 10,  11,  12]],

       [[ 13,  14,  15],
        [700, 800, 900],
        [ 16,  17,  18]]])

In [ ]:
mylist.ndim

3

####4-D tensors

In [ ]:
mylist=np.array([[[[1,2,3],[100,200,300],[4,5,6]]],[[[7,8,9],[400,500,600],[10,11,12]]],[[[13,14,15],[700,800,900],[16,17,18]]],[[[19,20,21],[1000,1100,1200],[22,23,24]]],[[[25,26,27],[1300,1400,1500],[28,29,30]]],[[[31,32,33],[1600,1700,1800],[34,35,36]]]])

In [ ]:
mylist

array([[[[   1,    2,    3],
         [ 100,  200,  300],
         [   4,    5,    6]]],


       [[[   7,    8,    9],
         [ 400,  500,  600],
         [  10,   11,   12]]],


       [[[  13,   14,   15],
         [ 700,  800,  900],
         [  16,   17,   18]]],


       [[[  19,   20,   21],
         [1000, 1100, 1200],
         [  22,   23,   24]]],


       [[[  25,   26,   27],
         [1300, 1400, 1500],
         [  28,   29,   30]]],


       [[[  31,   32,   33],
         [1600, 1700, 1800],
         [  34,   35,   36]]]])

In [ ]:
mylist.ndim

4

####5-D tensors

In [ ]:
mylist=np.array([[[[[1,2,3],[100,200,300],[4,5,6]]]],[[[[7,8,9],[400,500,600],[10,11,12]]]],[[[[13,14,15],[700,800,900],[16,17,18]]]],[[[[19,20,21],[1000,1100,1200],[22,23,24]]]],[[[[25,26,27],[1300,1400,1500],[28,29,30]]]],[[[[31,32,33],[1600,1700,1800],[34,35,36]]]]])

In [ ]:
mylist

array([[[[[   1,    2,    3],
          [ 100,  200,  300],
          [   4,    5,    6]]]],



       [[[[   7,    8,    9],
          [ 400,  500,  600],
          [  10,   11,   12]]]],



       [[[[  13,   14,   15],
          [ 700,  800,  900],
          [  16,   17,   18]]]],



       [[[[  19,   20,   21],
          [1000, 1100, 1200],
          [  22,   23,   24]]]],



       [[[[  25,   26,   27],
          [1300, 1400, 1500],
          [  28,   29,   30]]]],



       [[[[  31,   32,   33],
          [1600, 1700, 1800],
          [  34,   35,   36]]]]])

In [ ]:
mylist.ndim

5